### ISSUE TITLE
LaTex渲染的说明和测试

### ISSUE THREAD

**Issue by zafara-zd** [zafara-zd/blog#4]
https://zafara-zd.github.io/blog/math-test/ 

 LaTeX渲染已经在全站头部文件引入，可以直接使用，公式块上下使用$$标明，内联公式则用$.

最好不要让公式出现在文章摘要里。

Jekyll的默认文章摘要是第一段，但是我在使用中发现它选取摘要不是很稳定，因此加入了手动摘要分割线，默认为`

**Comment by Nifury** [comment]
Equation test
$$
\begin{equation}
x = a_0 + \cfrac{1}{a_1 
          + \cfrac{1}{a_2 
          + \cfrac{1}{a_3 + \cfrac{1}{a_4} } } }
\end{equation}
$$
